#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Load NVM for GUI clients
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# Ensure common paths are included
export PATH="$PATH:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

./node_modules/.bin/lint-staged
